config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users
    resources :notes

    get 'welcome/index'

    authenticated :user do
        root "notes#index", as: "authnticated_root"
    end

    root to: "welcome#index"
  
end

app/models/note.rb
class Note < ActiveRecord::Base

    # Associations
    belongs_to :user

    
    # Scopes
    scope :newest_first, -> {order("created_at DESC")}

    scope :by_user, lambda { |user| 
        where("notes.user_id = ?", user.id)
    }

    
    # Validations
    validates :title, 
                presence: true

    validates :content,
                presence: true,
                length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        # Associations
        has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        # add 'full_name' field to permitted params for sign-up
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
        end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    
    before_action :authenticate_user!
    before_action :set_note, only: [:show, :edit, :update, :destroy]

    # GET /notes
    # GET /notes.json
    def index
        @notes = Note.by_user(current_user).newest_first
    end

    # GET /notes/1
    # GET /notes/1.json
    def show
    end

    # GET /notes/new
    def new
        @note = current_user.notes.build
    end

    # GET /notes/1/edit
    def edit
    end

    # POST /notes
    # POST /notes.json
    def create
        @note = current_user.notes.build(note_params)

        respond_to do |format|
            if @note.save
                format.html { redirect_to @note, notice: 'Note was successfully created.' }
                format.json { render :show, status: :created, location: @note }
            else
                format.html { render :new }
                format.json { render json: @note.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /notes/1
    # PATCH/PUT /notes/1.json
    def update
        respond_to do |format|
            if @note.update(note_params)
                format.html { redirect_to @note, notice: 'Note was successfully updated.' }
                format.json { render :show, status: :ok, location: @note }
            else
                format.html { render :edit }
                format.json { render json: @note.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /notes/1
    # DELETE /notes/1.json
    def destroy
        
        @note.destroy
        
        respond_to do |format|
            format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

        # Use callbacks to share common setup or constraints between actions.
        def set_note
            @note = Note.find(params[:id])

        rescue ActiveRecord::RecordNotFound
            flash[:alert] = "Ooops! we could't find this record!"
            redirect_to :action =>"index"
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def note_params
            params.require(:note).permit(:title, :content)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
    %head
        %title Nevernote
        = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
        = csrf_meta_tags

    %body
        %nav.navbar.navbar-inverse.navbar-fixed-top
            .container
                .navbar-header
                    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
                        %span.sr-only Toggle navigation
                        %span.icon-bar
                        %span.icon-bar
                        %span.icon-bar
                    = link_to "Nevernote", root_path, class: "navbar-brand"
                .collapse.navbar-collapse#bs-example-navbar-collapse-1
                    - if user_signed_in?
                        %ul.nav.navbar-nav
                            %li= link_to "All Notes", root_path
                            %li= link_to "New Note", new_note_path
                    %ul.nav.navbar-nav.navbar-right
                        - if user_signed_in?
                            %li.navbar-text 
                                Signed in as:
                                = current_user.full_name
                        %li= link_to "Logout", destroy_user_session_path, method: :delete if user_signed_in?
                        %li= link_to "Log in", new_user_session_path if !user_signed_in?
                        %li= link_to "Register", new_user_registration_path if !user_signed_in?

        .container
            = content_tag :div, alert, class: "alert alert-danger" if alert
            = content_tag :div, notice, class: "alert alert-success" if notice

            = yield

        .container
            %hr

            %footer
                %p &copy; 2016 LykourgosTs@hotmail.com

        = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/notes/_form.html.haml
= simple_form_for(@note) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :content, input_html: {rows: 8}

  .form-group.form-group
    = f.button :submit, class: "btn btn-primary"

app/views/notes/edit.html.haml
%h2.page-header 
    Editing 
    = @note.title
.row
    .col-md-6.col-md-offset-3

        = render 'form'

        = link_to 'Show', @note
        \|
        = link_to 'Back', notes_path

app/views/notes/index.html.haml
%h2.page-header My notes

.row
    .col-md-12
        -unless @notes.blank?
            - @notes.each_slice(4) do |notes|
                .row
                    - notes.each do |note|
                        .col-md-3
                            %a{href: (url_for [note]), class: "note-well"}
                                .well
                                    %h4= note.title
                                    %p
                                        %small
                                            Created
                                            =  time_ago_in_words note.created_at
                                            ago
        - else
            .alert.alert-info
                %h3 Add Note
                %p It seems you haven't created any notes yet... Lets fix that. Why don't you create your first note below.

            = link_to "New Note", new_note_path, class: "btn btn-lg btn-primary"

app/views/notes/new.html.haml
%h2.page-header New note
.row
    .col-md-6.col-md-offset-3

        = render 'form'

        = link_to 'Back', notes_path

app/views/notes/show.html.haml
%h2.page-header= @note.title

= simple_format(@note.content)

.btn-group
    = link_to 'Back', notes_path, class: "btn btn-default"
    = link_to 'Edit', edit_note_path(@note), class: "btn btn-warning"
    = link_to 'Delete', note_path(@note), method: :delete, class: "btn btn-danger"

app/views/welcome/index.html.haml
.jumbotron
    %h1 What's Nevernote?

    %p 
        %strong 
            Nevernote
        is a demo web application developed in 
        %em
            Ruby on Rails
        and is similar to 
        %em
            Evernote.

    %p= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-primary"

.row
    .col-md-12
        .text-center 
            .lead "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante."
            Someone famous in 
            %cite{:title => "Nevernote"} Nevernote


%hr

.row
    .col-md-4
        %h2 Heading
        %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
        %p
            %a.btn.btn-default{:href => "#", :role => "button"} View details »
    .col-md-4
        %h2 Heading
        %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
        %p
            %a.btn.btn-default{:href => "#", :role => "button"} View details »
    .col-md-4
        %h2 Heading
        %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
        %p
            %a.btn.btn-default{:href => "#", :role => "button"} View details »